CHOOSE_MODEL: "Gemini" # OpenAI, Qwen, Gemini.

OPENAI_API_BASE: "https://api.openai.com/v1/chat/completions"
OPENAI_API_KEY: "sk-"  # set your openai api
OPENAI_API_MODEL: "gpt-4-vision-preview"
MAX_TOKENS: 300  # The max token limit for the response completion
TEMPERATURE: 0.0  # The temperature of the model: the lower the value, the more consistent the output of the model
REQUEST_INTERVAL: 10  # Time in seconds between consecutive GPT-4V requests

GEMINI_API_KEY: ""  # Set your gemini api
GEMINI_API_MODEL: "gemini-pro-vision"

QWEN_API_KEY: "sk-"  # The dashscope API key that gives you access to Qwen-VL model
QWEN_API_MODEL: "qwen-vl-max"

ANDROID_SCREENSHOT_DIR: "/sdcard/Pictures"  # Set the directory on your Android device to store the intermediate screenshots. Make sure the directory EXISTS on your phone!
ANDROID_XML_DIR: "/sdcard"
TASK_PATH: "task"
MIN_DIST: 30
PRIORITIZED_MODELS: "gemini-pro-version"



# real_time audio input settings
CHANNELS: 1
RATE: 16000
CHUNK: 1024
RECORD_SECONDS: 5  # record seconds
SILENCE_THRESHOLD: 0.01  # mute threshold
SILENCE_DURATION_TO_STOP: 2  # how long after the user stops talking to stop recording (seconds)
OUTPUT_PATH: "" # if you need to save input audio, change this to your path
MODEL_SIZE: "small" # choose from large-v2, medium, small (defualt), tiny
MODEL_PATH: "./scripts/WhisperModels/large-v2" # your faster-whisper model loacl path
